# Numpy
- 파이썬에서 제공하는 list, tuple로는 행렬에 관련된 작업을 하기 어렵다
- 행렬에 관련된 연산이나 작업 등을 위해 제공되는 라이브러리
- 수학에서의 행렬 또는 선형대수학에 관련된 기능들이 제공된다.

In [1]:
import numpy as np

### 리스트 (혹은 튜플)과의 비교

In [2]:
# 리스트
list1 = [10, 20, 30, 40, 50]
list2 = [60, 70, 80, 90, 100]

In [3]:
# 리스트 + 리스트
list3 = list1 + list2
list3

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [5]:
# 리스트 * 정수
list4 = list1 * 3
list4

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [7]:
# 행렬 생성(ndarray)
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([60, 70, 80, 90, 100])

In [9]:
# 행렬더하기
array3 = array1 + array2 
array3

array([ 70,  90, 110, 130, 150])

In [11]:
# 곱하기 : 수학에서 정한 연산방식을 그대로 따른다.
array4 = array1 * 3
array4

array([ 30,  60,  90, 120, 150])

### 행렬 생성
- 생성된 행렬의 타입은 다차원 행렬이라는 의미로 ndarray (n dimension array)라고 부른다. 

In [13]:
# 1차원 리스트
list1 = [10, 20, 30, 40, 50]
# 1차원 ndarray
# 함수 안에 리스트, 튜플, range 등과 같이 순서를 통해 데이터를 관리하는 요소를 넣어준다.
array1 = np.array([10, 20, 30, 40, 50])

In [15]:
print(type(list))
print(type(array1))

<class 'type'>
<class 'numpy.ndarray'>


In [16]:
print(list1)
print(array1)
print('-' * 30)
display(list1)
display(array1)

[10, 20, 30, 40, 50]
[10 20 30 40 50]
------------------------------


[10, 20, 30, 40, 50]

array([10, 20, 30, 40, 50])

In [19]:
# 2차원 리스트: 리스트 안에 리트트
list2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 2차원 행렬 : 2차원으로 구성된 행렬
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [21]:
print(list2)
print(array2)
print('-' * 30)
display(list2)
display(array2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 행렬과 타입의 관계

In [22]:
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([11.11, 22.22, 33.33])

In [23]:
# type 함수
# 파이썬의 type 함수는 매개변수로 들어오는 개체가 어떠한 클래스로 만들어졌는지를 확인할 수 있다.
print(type(array1))
print(type(array2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
# dtype
# 행렬이 관리하고 있는 값의 타입을 파악할 수 있다.
print(array1.dtype) # 32비트 정수
print(array2.dtype) # 64비트 실수

int32
float64


In [30]:
# 다양한 타입을 지정했을 경우
list3 = [True, 100, 11.11, '문자열']
# 행렬의 경우 하나의 행렬에 다양한 타입의 값을 넣었다면
# 가장 많은 종류의 값을 표현할 수 있는 타입으로 변환되어 한 가지 타입만 갖게 된다. 
# 논리형 -> 정수형 -> 실수형 -> 문자열형
array3 = np.array([True, 100, 11.11, '문자열'])  #True가 1로 바뀐 이유 = 수학에서 행렬을 그렇게 정의함. 행렬에서는 같은 타입만 담을 수 있음. 

display(list3)
display(array3)

[True, 100, 11.11, '문자열']

array(['True', '100', '11.11', '문자열'], dtype='<U32')

In [32]:
# 행렬 생성 시 타입을 결정할 수 있다.

# 논리형 : bool, 정수: int, 실수: float, 문자열: str
array4 = np.array([0, 1, 2, 3, 4], dtype = 'float')
array5 = np.array([0, 1, 2, 3, 4], dtype = 'bool')

display(array4) 
display(array5)

array([0., 1., 2., 3., 4.])

array([False,  True,  True,  True,  True])

In [41]:
# numpy가 제공하는 타입을 설정할 수도 있다.
array6 = np.array([0, 1, 2, 3, 4], dtype=np.int32)
array7 = np.array([0, 1, 2, 3, 4], dtype=np.bool_)

display(array6)
display(array7)

array([0, 1, 2, 3, 4])

array([False,  True,  True,  True,  True])

In [42]:
# 이미 생성되어 있는 행렬이 가지고 있는 원소들을 추출하여 새로운 행렬을 만들때 타입을 정할 수 있다.
array8 = np.array([10, 20, 30, 40, 50])
array9 = array8.astype('str')
display(array8)
display(array9)

array([10, 20, 30, 40, 50])

array(['10', '20', '30', '40', '50'], dtype='<U11')

### 행렬 생성 함수

In [43]:
# 관리할 값들을 지정하여 행렬을 생성한다.
array1 = np.array([10, 20, 30, 40, 50])
array1

array([10, 20, 30, 40, 50])

In [44]:
# 0 행렬
# 원소가 0으로 채워진 행렬을 의미함.
# 0이 5개 있는 1차원 행렬
# 0의 개수를 지정한다.
array2 = np.zeros(5)
# 0으로 채워진 3행 4열 행렬
# 0행렬의 행, 열의 수를 지정한다.
array3 = np.zeros([3, 4])

display(array2)
display(array3)

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
# 원소가 1로 채워진 행렬을 의미함.
# 1이 5개 있는 1차원 행렬
# 1의 개수를 지정한다.
array4 = np.ones(5)
# 1로 채워진 3행 4열 행렬
# 행렬의 행, 열의 수를 지정한다.
array5 = np.ones([3, 4])

display(array4)
display(array5)

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
# n으로 채워진 행렬
# 7이 5개 있는 1차원 행렬
# 숫자의 개수와 관리할 숫자를 지정한다
array6 = np.full(5, 7)

# 7로 채워진 3행 4열 행렬
# [행렬의 행의 수, 행렬의 열의 수]와 채울 숫자를 지정해준다.
array7 = np.full([3, 4], 7)

display(array6)
display(array7)

array([7, 7, 7, 7, 7])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [47]:
# 랜덤값으로 채워진 행렬을 생성한다. 
# 0 <= n < 1

# 랜덤 숫자 5개로 이루어진 1차원 행렬
array8 = np.random.random(5)
# 랜덤 숫자로 채워진 3행 4열 행렬
array9 = np.random.random([3, 4])

display(array8)
display(array9)

array([0.98220809, 0.03149371, 0.81035806, 0.01998084, 0.47198953])

array([[0.2127271 , 0.33470415, 0.14382335, 0.760801  ],
       [0.87269239, 0.79142477, 0.38914147, 0.63916921],
       [0.74369935, 0.71512409, 0.01680282, 0.6309904 ]])

In [48]:
# 범위를 정해서 정수 값을 랜덤하게 추출한다.
# 랜덤 정수값 5개로 이루어진 1차원 행렬
# 0 ~ 10 - 1
# 시작값, 끝값, 개수
array10 = np.random.randint(0, 10, 5)
# 랜덤 정수값으로 채워진 3행 4열 행렬
# 0 ~ 10 - 1, 3행 4열
# 시작값, 끝값, [행의 개수, 열의 개수]
array11 = np.random.randint(0, 10, [3, 4])

display(array10)
display(array11)

array([4, 8, 1, 1, 9])

array([[6, 5, 6, 1],
       [5, 1, 0, 2],
       [0, 1, 9, 9]])

In [50]:
# 특정 범위를 가진 행렬을 생성한다.
# 0 ~ 6 -1 까지
array12 = np.arange(6)
array12

array([0, 1, 2, 3, 4, 5])

In [51]:
# 3 ~ 13 - 1까지
array13 = np.arange(3, 13)
array13

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
### 행렬의 산술 연산
array1 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [54]:
# 행렬과 행렬 간의 산술 연산
# 행렬의 각 원소를 1:1 매칭하여 연산을 하고 그 결과가 담겨 있는 행렬을 반환한다.
# 연산을 하는 두 행렬의 행과 열의 수가 일치해야 한다.
a1 = array1 + array2
a2 = array1 - array2
a3 = array1 * array2
a4 = array1 / array2
a5 = array1 ** array2
a6 = array1 // array2
a7 = array1 % array2

display(a1, a2, a3, a4, a5, a6, a7)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

array([[        10,        400,      27000],
       [   2560000,  312500000, -588640256],
       [1977693568,          0, -779249152]])

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
# 행렬과 숫자 간의 산술 연산
# 행렬의 각 원소에 숫자와의 연산을 각각 수행한 결과를 반환한다.
a1 = array1 + 10
a2 = array1 - 10
a3 = array1 * 10
a4 = array1 / 10
a5 = array1 ** 10
a6 = array1 // 10
a7 = array1 % 10

display(a1, a2, a3, a4, a5, a6, a7)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

array([[ 1410065408,   797966336,   716276736],
       [ 1073741824, -1957116928,  -972029952],
       [ 1759093760,           0, -1412946944]], dtype=int32)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

### 인덱싱과 슬라이싱
- 인덱싱 : 값 하나를 가져오는 것
- 슬라이싱: 원하는 부분의 값을 가져오는 것

In [57]:
# 1차원
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [58]:
# 0부터 1씩 증가하는 순서값
# 앞에서 부터
print(list1[0])
print(list1[1])
print(array1[0])
print(array1[1])

10
20
10
20


In [59]:
# -1부터 1씩 감소하는 순서값
# 뒤에서부터
print(list1[-1])
print(list1[-2])
print(array1[-1])
print(array[-2])

100
90
100
130


In [60]:
# 2 ~ 6 -1 까지
print(list1[2:6])
print(array[2:6])
# 처음부터 6 - 1까지
print(list1[:6])
print(array1[:6])
# 2 ~ 끝까지
print(list1[2:])
print(array1[2:])

[30, 40, 50, 60]
[110 130 150]
[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60]
[30, 40, 50, 60, 70, 80, 90, 100]
[ 30  40  50  60  70  80  90 100]


In [61]:
list1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [62]:
# 2행 3열의 데이터를 가져온다.
print(list1[1][2])
print(array1[1][2])
print(array1[1,2]) #행렬에서만 가능한 문법

6
6
6


In [63]:
# 1 ~ 3 - 1 행, 1 ~ 3 - 1 열의 데이터를 가져온다.
display(list1[1:3][1:3]) # 엉뚱한 결과
display(array1[1:3][1:3]) # 엉뚱한 결과
display(array1[1:3, 1:3])

[[7, 8, 9]]

array([[7, 8, 9]])

array([[5, 6],
       [8, 9]])

In [67]:
array1 = np.array([10, 20, 30, 40, 50])
# 순서값을 지정하여 그 순서에 해당하는 값들을 가져올 수 있다.
array2 = array1[[0, 1, 4]]
array2

array([10, 20, 50])

In [69]:
# True나 False로 구성된 요소를 넣어주면 True에 해당하는 것만 가져온다.
# 원소의 개수와 동일한 개수로 되어 있어야 한다.
array3 = array1[[True, False, True, False, True]]
array3

array([10, 30, 50])

In [75]:
array4 = np.arange(100)
array5 = array4 % 3 == 0 
array6 = array4[array5]
array6

array([], dtype=int32)

In [77]:
array4 = np.arange(100)
array6 = array4[array4 % 3 == 0]
array6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])